Packaging fixes

diff --git a/packages/ntopng.spec.in b/packages/ntopng.spec.in
--- a/packages/ntopng.spec.in
+++ b/packages/ntopng.spec.in
@@ -16,20 +16,13 @@ Web-based traffic monitoring
 
 %setup -q
 
+# Disable stripping
+%global _enable_debug_package 0
+%global debug_package %{nil}
+%global __os_install_post /usr/lib/rpm/brp-compress %{nil}
+
 %build
-/bin/rm -rf $HOME/rpmbuild/BUILD/ntopng $HOME/rpmbuild/BUILD/ntopng-@NTOPNG_VERSION@
-cd $HOME/rpmbuild/BUILD/
-git clone https://github.com/ntop/ntopng.git
-ln -s $HOME/rpmbuild/BUILD/ntopng $HOME/rpmbuild/BUILD/ntopng-@NTOPNG_VERSION@
-if test -d $HOME/ntopng/pro; then
-    cp -r $HOME/ntopng/pro $HOME/rpmbuild/BUILD/ntopng-@NTOPNG_VERSION@
-fi
-cd $HOME/rpmbuild/BUILD/ntopng-@NTOPNG_VERSION@
-./autogen.sh
-PATH=/usr/bin:/bin:/usr/sbin:/sbin
-CFLAGS="$RPM_OPT_FLAGS" ./configure
-make
-if test -d "pro"; then cd pro; make build; fi
+if ! test -f "$HOME/ntopng/pro/utils/snzip"; then echo "snzip missing"; exit; fi
 #
 
 # Installation may be a matter of running an install make target or you
@@ -39,44 +32,35 @@ PATH=/usr/bin:/bin:/usr/sbin:/sbin
 if [ -d $RPM_BUILD_ROOT ]; then
 	\rm -rf $RPM_BUILD_ROOT
 fi
-#
-# "T.J. Yang" <tjyang2001@gmail.com>
-#
-#mkdir -p $RPM_BUILD_ROOT/etc/ntopng
-#cat >$RPM_BUILD_ROOT/etc/ntopng/ntopng.conf.sample <<_EOT_
-#-G=/var/tmp/ntopng.pid
-#_EOT_
-#cat >$RPM_BUILD_ROOT/etc/ntopng/ntopng.start <<_EOT_
-#_EOT_
 
 mkdir -p $RPM_BUILD_ROOT/usr/bin $RPM_BUILD_ROOT/usr/share/ntopng $RPM_BUILD_ROOT/usr/share/man/man8 
 mkdir -p $RPM_BUILD_ROOT/etc/init.d $RPM_BUILD_ROOT/etc/logrotate.d
-cp $RPM_BUILD_DIR/ntopng-%{version}/ntopng $RPM_BUILD_ROOT/usr/bin
-cp $RPM_BUILD_DIR/ntopng-%{version}/ntopng.8 $RPM_BUILD_ROOT/usr/share/man/man8/ 
-cp -r $RPM_BUILD_DIR/ntopng-%{version}/httpdocs $RPM_BUILD_DIR/ntopng-%{version}/scripts $RPM_BUILD_ROOT/usr/share/ntopng
-
-if test -d "$RPM_BUILD_DIR/ntopng-%{version}/pro"; then
-   cd $RPM_BUILD_DIR/ntopng-%{version}/pro; make; cd -
+cp $HOME/ntopng/ntopng $RPM_BUILD_ROOT/usr/bin
+cp $HOME/ntopng/ntopng.8 $RPM_BUILD_ROOT/usr/share/man/man8/ 
+cp -r $HOME/ntopng/httpdocs $HOME/ntopng/scripts $RPM_BUILD_ROOT/usr/share/ntopng
+mv $RPM_BUILD_ROOT/usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem.dummy $RPM_BUILD_ROOT/usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem
+if test -d "$HOME/ntopng/pro"; then
+   cd $HOME/ntopng/pro; make; cd -
    mkdir $RPM_BUILD_ROOT/usr/share/ntopng/pro
-   cp -r $RPM_BUILD_DIR/ntopng-%{version}/pro/httpdocs $RPM_BUILD_ROOT/usr/share/ntopng/pro
-   cp -r $RPM_BUILD_DIR/ntopng-%{version}/pro/scripts $RPM_BUILD_ROOT/usr/share/ntopng/pro
+   cp -r $HOME/ntopng/pro/httpdocs $RPM_BUILD_ROOT/usr/share/ntopng/pro
+   cp -r $HOME/ntopng/pro/scripts $RPM_BUILD_ROOT/usr/share/ntopng/pro
    cd $RPM_BUILD_ROOT/usr/share/ntopng/scripts/lua; ln -s ../../pro/scripts/lua pro
-   find $RPM_BUILD_ROOT/usr/share/ntopng/pro -name "*.lua" -type f -exec $RPM_BUILD_DIR/ntopng-%{version}/pro/utils/snzip -c -i {} -o {}r \;
+   find $RPM_BUILD_ROOT/usr/share/ntopng/pro -name "*.lua" -type f -exec $HOME/ntopng/pro/utils/snzip -c -i {} -o {}r \;
    find $RPM_BUILD_ROOT/usr/share/ntopng/pro -name "*.lua" -type f -exec /bin/rm  {} ';'
    find $RPM_BUILD_ROOT/usr/share/ntopng/pro -name "*.luar" | xargs rename .luar .lua
 fi
 
 
-#cp $RPM_BUILD_DIR/ntopng-%{version}/packages/etc/init/ntopng.conf $RPM_BUILD_ROOT/etc/init
+#cp $HOME/ntopng/packages/etc/init/ntopng.conf $RPM_BUILD_ROOT/etc/init
 if test -d "/etc/systemd"; then
    mkdir -p $RPM_BUILD_ROOT/etc/systemd/scripts/
    mkdir -p $RPM_BUILD_ROOT/etc/systemd/system/
-   cp $RPM_BUILD_DIR/ntopng-%{version}/packages/etc/init.d/ntopng    $RPM_BUILD_ROOT/etc/systemd/scripts/
-   cp $RPM_BUILD_DIR/ntopng-%{version}/packages/etc/systemd/system/ntopng.service    $RPM_BUILD_ROOT/etc/systemd/system/
+   cp $HOME/ntopng/packages/etc/init.d/ntopng    $RPM_BUILD_ROOT/etc/systemd/scripts/
+   cp $HOME/ntopng/packages/etc/systemd/system/ntopng.service    $RPM_BUILD_ROOT/etc/systemd/system/
 else
-   cp $RPM_BUILD_DIR/ntopng-%{version}/packages/etc/init.d/ntopng    $RPM_BUILD_ROOT/etc/init.d
+   cp $HOME/ntopng/packages/etc/init.d/ntopng    $RPM_BUILD_ROOT/etc/init.d
 fi
-cp $RPM_BUILD_DIR/ntopng-%{version}/packages/etc/logrotate.d/ntopng    $RPM_BUILD_ROOT/etc/logrotate.d/
+cp $HOME/ntopng/packages/etc/logrotate.d/ntopng    $RPM_BUILD_ROOT/etc/logrotate.d/
 find $RPM_BUILD_ROOT -name ".git" | xargs /bin/rm -rf
 find $RPM_BUILD_ROOT -name ".svn" | xargs /bin/rm -rf
 find $RPM_BUILD_ROOT -name "*~"   | xargs /bin/rm -f
@@ -125,6 +109,7 @@ if test ! -e /usr/local/bin/ntopng ; then ln -s /usr/bin/ntopng /usr/local/bin/n
 %endif
 
 %postun
-echo 'Removing /usr/local/bin/ntopng link'
-rm -f /usr/local/bin/ntopng > /dev/null 2>&1
-
+if [ $1 == 0 ] ; then
+    echo 'Removing /usr/local/bin/ntopng link'
+    rm -f /usr/local/bin/ntopng > /dev/null 2>&1
+fi
